### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by nickhendo** [myriky/flutter_siri_suggestions#11]
Are there any intentions here to add null safety?

**Comment by greentee5** [comment]
@nickhendo which IOS version are you using while getting this issue?

**Comment by nickhendo** [comment]
@greentee5 This isn't an IOS version related issue. More just that it's not a null-safe library. Looks as though there is a PR outstanding addressing null-safety, among other things.

**Comment by myriky** [comment]
migrated 👍
