### ISSUE TITLE
Android V2 Embedding

### ISSUE THREAD

**Issue by nhlhelen** [myriky/flutter_siri_suggestions#14]
The plugins flutter_siri_suggestions use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: [https://flutter.dev/go/android-plugin-migration](url) . 

In release sdk 2.5.0

**Comment by myriky** [comment]
check it out new version :)
