### ISSUE TITLE
onLaunch callback always empty map

### ISSUE THREAD

**Issue by stx** [myriky/flutter_siri_suggestions#2]
@myriky 

Hi, thanks for the plugin.

`FlutterSiriSuggestions.instance.configure(onLaunch: ...)` only returns `{}`. iPhone 11 on iOS 13. Is there a fix for this, am I doing something wrong, or is it not implemented?

**Comment by stx** [comment]
I suspected this is related to NSUserActivityTypes, but still not working with Siri capability added to entitlements and this in `Info.plist`:

```
	<key>NSUserActivityTypes</key>
	<array>
		<string>flutter_siri_suggestions</string>
	</array>
```

**Comment by myriky** [comment]
@stx thank you for let me know.
i'll figure out ASAP 😄

**Comment by tampiss** [comment]
Same issue :-/

**Comment by Niek** [comment]
Same

**Comment by myriky** [comment]
i'm sorry for late.
checkout v1.0.2 🎉
