### ISSUE TITLE
Call (buildActivity) multiple times with different keys, it creates always the last suggestion

### ISSUE THREAD

**Issue by martinsedoo1** [myriky/flutter_siri_suggestions#4]
@override
      void initState() {
       FlutterSiriSuggestions.instance.buildActivity(FlutterSiriActivity(
           "new app",
           "firstActivity",
           isEligibleForSearch: true,
           isEligibleForPrediction: true,
           contentDescription: "Did you enjoy that?",
           suggestedInvocationPhrase: "open my app",
      ));

     FlutterSiriSuggestions.instance.buildActivity(FlutterSiriActivity(
        "new app",
        "secondActivity",
         isEligibleForSearch: true,
         isEligibleForPrediction: true,
         contentDescription: "Did you enjoy that?",
         suggestedInvocationPhrase: "open my app",
    ));

    FlutterSiriSuggestions.instance.configure(
        onLaunch: (Map<String, dynamic> message) async {
      if (message["key"] == "firstActivty") {
        //firstSiriActivity
      } else if (message["key"] == "secondActivity") {
        //secondSiriActivity
      }
    });
    super.initState();
    }

**Comment by martinsedoo1** [comment]
`@override
  void initState() {
    FlutterSiriSuggestions.instance.buildActivity(FlutterSiriActivity(
      "new app",
      "firstActivity",
      isEligibleForSearch: true,
      isEligibleForPrediction: true,
      contentDescription: "Did you enjoy that?",
      suggestedInvocationPhrase: "open my app",
    ));
    FlutterSiriSuggestions.instance.buildActivity(FlutterSiriActivity(
      "new app",
      "secondActivity",
      isEligibleForSearch: true,
      isEligibleForPrediction: true,
      contentDescription: "Did you enjoy that?",
      suggestedInvocationPhrase: "open my app",
    ));

    FlutterSiriSuggestions.instance.configure(
        onLaunch: (Map<String, dynamic> message) async {
      if (message["key"] == "firstActivty") {
        //firstSiriActivity
      } else if (message["key"] == "secondActivity") {
        //secondSiriActivity
      }
    });
    super.initState();
  }`

**Comment by myriky** [comment]
did you check second parameter?

**Comment by myriky** [comment]
also i'm checking now build fail problem in Android.

**Comment by myriky** [comment]
I found problems that do not work properly when adding one more activities at the same time. thank you :)

**Comment by myriky** [comment]
checkout 1.0.2+hotfix1
sorry for inconvenience
