### ISSUE TITLE
Is there a limit for amount of SiriSuggestion I can add?

### ISSUE THREAD

**Issue by Livinglist** [myriky/flutter_siri_suggestions#5]
I tried to achieve a feature where users can search for content in my app in the spotlight (like a dictionary) so I decided to add all the entry to the SiriSuggestion (about 2000 of them), but I have found that only 5 of those are discoverable in the spotlight. So my question is that is there a limit for amount of SiriSuggestion I can add or I am not doing it the right way?

**Comment by myriky** [comment]
In fact, I have never tried so much.
NSUserActivity is expected to be unlimited. nevertheless, iOS only shows five latest activities.

check it out documents of NSUserActivity
=> https://developer.apple.com/documentation/foundation/nsuseractivity

**Comment by Livinglist** [comment]
> In fact, I have never tried so much.
> NSUserActivity is expected to be unlimited. nevertheless, iOS only shows five latest activities.
> 
> check it out documents of NSUserActivity
> => https://developer.apple.com/documentation/foundation/nsuseractivity

I tried the following:

```
Future.forEach(Iterable.generate(2000, (_) => _), addSuggestion);

Future addSuggestion(int i) async {
    print("adding the $i");
    return FlutterSiriSuggestions.instance.buildActivity(FlutterSiriActivity(i.toString(), i.toString(),
        isEligibleForSearch: true, isEligibleForPrediction: true, contentDescription: i.toString(), suggestedInvocationPhrase: "open my app"));
}
```

but only a few of them will be discoverable in the spotlight search.

**Comment by Livinglist** [comment]
> In fact, I have never tried so much.
> NSUserActivity is expected to be unlimited. nevertheless, iOS only shows five latest activities.
> 
> check it out documents of NSUserActivity
> => https://developer.apple.com/documentation/foundation/nsuseractivity

I seem to find a bug. Once a FlutterSiriActivity is added, it won't be valid(usable) once you quit the app.
